### ISSUE TITLE
Improve link to required course

### ISSUE THREAD

**Issue by amit-tewari** [ewallah/moodle-enrol_coursecompleted#30]
## Current behavior:

- there are 3 courses: `common 101`, `C1 201` and `C2 201`
- `C1 201` and `C2 201` need `common 101` to be completed for auto enrollment
![image](https://github.com/ewallah/moodle-enrol_coursecompleted/assets/440557/b0731617-1568-4e5d-9323-41058513593d)

- visiting `C1 201`, by clicking on `C1 201`  link in `Available courses` , takes to a page like this (https://SITE/enrol/index.php?id=20) 
![image](https://github.com/ewallah/moodle-enrol_coursecompleted/assets/440557/c7665658-d308-4378-ad83-e27114bf4194)

- Link `common 101` on this page takes to https://SITE/enrol/index.php?id=20, that is to `C1 201`

## Expected behavior:

- Link `common 101` on this page should take user to `common 101`  (https://SITE/course/view.php?id=19) **instead of** `C1 201` (https://SITE/enrol/index.php?id=20) 

## Where this might be fixed
https://github.com/ewallah/moodle-enrol_coursecompleted/blob/69bf5dc4100945ece7e124cf98ba55457227b862/lib.php#L90  seems the function generating this URL, but I am not very good with Moodle coding in general or with Moodle plugins, so unable to submit a proper PR for fix.

## Plugin and Moodle versions

- **Course completed enrolment**: enrol_coursecompleted | v4.0.4 : 2023051000
- **Moodle:** 4.2

Plugin is working as expected otherwise.

Thank you for writing and maintaining this very useful plugin, and having a look at this issue.

**Comment by amit-tewari** [comment]
https://github.com/ewallah/moodle-enrol_coursecompleted/blob/b38cfa78afe802db22fc5d8cc29d4f778b765a8f/lib.php#L90 is what I found to be installed on server, not https://github.com/ewallah/moodle-enrol_coursecompleted/blob/69bf5dc4100945ece7e124cf98ba55457227b862/lib.php#L90 (main branch)

**Comment by ewallah** [comment]
THX for your comments. I will have a look ASAP.

**Comment by ewallah** [comment]
Hello Amit,

your strings are hard coded in the [template file](https://github.com/ewallah/moodle-enrol_coursecompleted/pull/31/commits/9cf823d0630f35ad82ff5b96a2f4182e3fa7ff8b#diff-f5b89026d22eb62812272d3b6775a94b7c5850fc18ef9120b07bad7d301cc646R45), so in a multi language environment. students will also see the English text. Perhaps you could do your changes by [customizing the language strings](https://docs.moodle.org/402/en/Language_customisation)?

Why did you change the enrol/index.php to course/view.php?  IMHO the first work better when a user is not logged in, otherwise the user is immediately forwarded to the latter.

**Comment by amit-tewari** [comment]
Hello @ewallah ,

> your strings are hard coded...

will check out language strings.

> Why did you change the enrol/index.php to course/view.php?...

My observation, as logged in user, was:
If we are going to `/course/view.php` and not enrolled already, automatic redirection happens to `/enrol/index.php` of the required course.
But if we go to `/enrol/index.php` directly and one is already enrolled to the other course, automatic redirection happens to the course which has dependencies.

> when a user is not logged in, otherwise the user is immediately forwarded to the latter.

I did not observe this behavior with the changes I have, for the setup described in original issue description. That said, i have to admit my setup is very minimal one from stock Moodle install with only enrol_coursecompleted plugin, and there could be cases where this might be true.
If this helps, and you wish, I can create a user and share site details with you for any checks you would like to perform.

I shall try to explore language strings for customization.

**Comment by amit-tewari** [comment]
Fixed by https://github.com/ewallah/moodle-enrol_coursecompleted/commit/75f98025fbada33f4e1d21ec9d1eb008b8e16437.

Thank you @rdebleu and @ewallah .

**Comment by pateljj04** [comment]
I think there is still an issue on this page - For example, if **Course 1** is pre-requisite to **Course 2** - when you click on **Course 2** you get a learning path with the following message  "You will be enrolled in this course when you complete course **Course 1**" Here the Course 1 is actually linked to Course 2 and not Course 1. See screenshot
![SCR-20230815-ojwq](https://github.com/ewallah/moodle-enrol_coursecompleted/assets/404871/c7b90b49-d4d3-46a3-94ab-a1ea213e196b)

**Comment by ewallah** [comment]
Hi @pateljj04 

In [line 392](https://github.com/ewallah/moodle-enrol_coursecompleted/blob/69bf5dc4100945ece7e124cf98ba55457227b862/lib.php#L392) I need to call the array_unique function to remove double entries because we work linear (1 dimension).

I could use a framework like [vis network](https://visjs.github.io/vis-network/examples/network/basic_usage/standalone.html) to show more dimensions and a more correct representation of all options. But the open source version of this plugin needs to be low bandwidth and low maintenance friendly .

**Comment by Vozsvarozs** [comment]
Hi @ewallah !

There are still issues with the course links used. I think 1) is the same @pateljj04 mentioned.

1) The link in "_You will be enrolled in this course when you complete course <course name & link>_" leads to the course the where the user currently is, i.e. to the one currently not available for enrollment. However, the course name displayed is the proper one.
(E.g., in a learning path Course 1 (id=1) -> Course 2 (id=2), when viewing course Course 2, "Course 1" is in the text, but the link has id=2)
2) In cases with 3 or more courses, the displayed learning path has the order of the prerequisite courses reversed.
I.e., for a path A -> B -> C -> D, if user views course D, the order displayed is C -> B -> A -> D. If user views course C, then the path is B -> A -> C -> D. The order is correct when user views B, because only 1 course is a prerequisite.

( Moodle 4.1.1+, plugin v4.0.6 (2023080900) )

**Comment by ewallah** [comment]
THX for the report.

As this feature only creates misunderstandings and errors, I seriously think of removing this part of the plugin in the next release.
Unless someone comes up with a good alternative....

**Comment by Vozsvarozs** [comment]
In line 112:
	`'coureurl' => new moodle_url('/course/view.php', ['id' => $instance->customint1]),`
the 's' is missing from 'coureurl'. It should be 'courseurl' - changing it solves the issue.
(Btw, if $course is already used in the previous line (#111) to get the title/fullname of the course, $instance->customint1 could be $course->id instead, for better readability)

In line 407:
	`$arr = array_merge($arr, $this->search_parents($parent, $level));`
Changing the order of the parameters ($arr and $this... to $this... and $arr) solves the issue, as that way parent items are placed before children items.

**Comment by ewallah** [comment]
THX @Vozsvarozs,

Excellent bug spotting (coureurl).
Excellent suggestion to alter the order of parameters.

Implemented immediately.
